namespace Vintagestory.API.Client;

public enum EnumShaderProgram
{
	Standard = 1,
	Particlescube = 2,
	Particlesquad = 3,
	Sky = 5,
	Nightsky = 7,
	Woittest = 8,
	Transparentcompose = 9,
	Debugdepthbuffer = 10,
	Helditem = 11,
	Chunkopaque = 12,
	MultiTextureTest = 13,
	Chunkliquid = 14,
	Decals = 15,
	Final = 16,
	Gui = 17,
	Blur = 18,
	Chunktransparent = 19,
	Findbright = 20,
	Chunktopsoil = 21,
	Godrays = 22,
	Autocamera = 23,
	Blockhighlights = 24,
	Wireframe = 25,
	Entityanimated = 26,
	Luma = 27,
	Blit = 28,
	Shadowmap = 29,
	Particlesquad2d = 30,
	Shadowmapentityanimated = 31,
	Chunkshadowmap = 32,
	Texture2texture = 33,
	Celestialobject = 34,
	Guitopsoil = 35,
	Colorgrade = 37,
	Guigear = 38,
	Ssao = 39,
	Bilateralblur = 40,
	Chunkliquiddepth = 41,
	Chunkshadowmap_NoSSBOs = 42
}
